// ynab-formatter/src/app/page.tsx
import Image from 'next/image'

export default function Home() {
  return (
    <main>
      <div className="container">
        <nav className="navbar navbar-dark bg-primary">
          <span className="h1 navbar-brand mb-0">YNAB Formatter</span>
          <ul className="navbar-nav">
            <li className="nav-item">
              <a className="nav-link" href="https://app.youneedabudget.com">YNAB</a>
            </li>
          </ul>
        </nav>
        <div className="row">
          <div className="col-md-6">
            <h2>Input</h2>
              <div className="form-group">
                <label htmlFor="transactionSource">Transaction Source</label>
                <select id="transactionSource">
                  <option value="bank">Bank</option>
                  <option value="ticketduo">TicketDuo</option>
                  <option value="norwegian">Bank of Norwegian</option>
                  <option value="kplussa">K-Plussa Mastercard</option>
                </select>
              </div>

            <textarea cols={20} rows={20}></textarea>
          </div>
          <div className="col-md-6">
            <h2>Output</h2>
            <table className="table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Payee</th>
                  <th>Outflow</th>
                  <th>Inflow</th>
                </tr>
              </thead>
              <tbody>
              <tr>
                <td>dd.mm.yyyy</td>
                <td>ACME corp</td>
                <td className="text-right">2.00€</td>
                <td className="text-right">0.00€</td>
              </tr>
              </tbody>
            </table>
            <button className="btn btn-primary">Download CSV</button>
          </div>
        </div>
      </div>
    </main>
  )
}

// src/app/app.component.ts
import {Component, OnInit} from '@angular/core';
import {FormControl} from '@angular/forms';
import { saveAs } from 'file-saver';

import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/distinctUntilChanged';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/concat';
import 'rxjs/add/observable/of';
import {Observable} from 'rxjs/Observable';
import {ParserService} from "./parser";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  bankTransactions = new FormControl();
  ynabTransactions = [];

  constructor(private parser: ParserService) {}

  ngOnInit(): void {
    this.bankTransactions
      .valueChanges
      .debounceTime(300)
      .distinctUntilChanged()
      .map(input => this.parser.parse(input))
      .catch((err, caught) => {
        console.error(err);
        return Observable.of([]).concat(caught)
      })
      .subscribe(transactions => this.ynabTransactions = transactions);
  }

  download(): void {
    const blob = new Blob([this.transactionsToCSV(this.ynabTransactions)], {type: 'text/csv;charset=utf-8'});
    saveAs(blob, 'transactions.csv');
  }

  transactionsToCSV(transactions: any[]): string {
    const csvRows = transactions.map(transaction => {
      const outflowStr = (transaction.outflow) ? transaction.outflow.toFixed(2) : '';
      const inflowStr = (transaction.inflow) ? transaction.inflow.toFixed(2) : '';
      return transaction.date + ','
        + transaction.payee.replace(/,/g, '') + ','
        + ','
        + ','
        + outflowStr + ','
        + inflowStr
    });
    let csv = 'Date,Payee,Category,Memo,Outflow,Inflow\n';
    csvRows.forEach(row => {
      csv += row + '\n'
    });
    return csv;
  }
}


<div class="container">
  <nav class="navbar navbar-dark bg-primary">
    <span class="h1" class="navbar-brand mb-0">YNAB Formatter</span>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="https://app.youneedabudget.com">YNAB</a>
      </li>
    </ul>
  </nav>
  <div class="row">
    <div class="col-md-6">
      <h2>Input</h2>
        <div class="form-group">
          <label for="transactionSource">Transaction Source</label>
          <select id="transactionSource" [formControl]="transactionType">
            <option value="bank">Bank</option>
            <option value="ticketduo">TicketDuo</option>
            <option value="norwegian">Bank of Norwegian</option>
            <option value="kplussa">K-Plussa Mastercard</option>
          </select>
        </div>

      <textarea cols="20" rows="20" [formControl]="bankTransactions"></textarea>
    </div>
    <div class="col-md-6">
      <h2>Output</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Payee</th>
            <th>Outflow</th>
            <th>Inflow</th>
          </tr>
        </thead>
        <tbody>
        <tr *ngFor="let transaction of ynabTransactions">
          <td>{{transaction.date}}</td>
          <td>{{transaction.payee}}</td>
          <td class="text-right">{{transaction.outflow.toFixed(2)}}€</td>
          <td class="text-right">{{transaction.inflow.toFixed(2)}}€</td>
        </tr>
        </tbody>
      </table>
      <button class="btn btn-primary" [disabled]="!ynabTransactions.length" (click)="download()">Download CSV</button>
    </div>
  </div>
</div>
